"""add close_time to open_positions

Revision ID: 2691dd5c779d
Revises: b2aab9d0dc73
Create Date: 2026-04-21 17:41:15.828315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2691dd5c779d'
down_revision: Union[str, Sequence[str], None] = 'b2aab9d0dc73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('open_positions', sa.Column('close_time', sa.TIMESTAMP(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('open_positions', 'close_time')
    # ### end Alembic commands ###
