"""create portfolio snapshots

Revision ID: 70981d86c4a2
Revises: e472f9c1e70e
Create Date: 2026-04-06 23:52:17.918787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70981d86c4a2'
down_revision: Union[str, Sequence[str], None] = 'e472f9c1e70e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolio_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('total_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('cash_balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('positions_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('open_positions', sa.Integer(), nullable=False),
    sa.Column('realized_pnl', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('snapshot_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('portfolio_snapshots')
    # ### end Alembic commands ###
