"""drop guardian_synced and guardian_closed from run_cycles

Revision ID: 9da3dc2c8cbe
Revises: 2691dd5c779d
Create Date: 2026-04-22 17:44:18.386803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9da3dc2c8cbe'
down_revision: Union[str, Sequence[str], None] = '2691dd5c779d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('run_cycles', 'guardian_synced')
    op.drop_column('run_cycles', 'guardian_closed')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('run_cycles', sa.Column('guardian_closed', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('run_cycles', sa.Column('guardian_synced', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
