"""add market_category_context table

Revision ID: b2aab9d0dc73
Revises: 70981d86c4a2
Create Date: 2026-04-14 16:02:19.900018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b2aab9d0dc73'
down_revision: Union[str, Sequence[str], None] = '70981d86c4a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_category_context',
    sa.Column('category_key', sa.Text(), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('resolution_desc_template', sa.Text(), nullable=False),
    sa.Column('uses_slug', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('resolution_rules', sa.Text(), nullable=False),
    sa.Column('known_disputes', sa.Text(), nullable=False),
    sa.Column('edge_cases', sa.Text(), nullable=False),
    sa.Column('risk_questions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sources', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('last_refreshed_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('refresh_duration_seconds', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('category_key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('market_category_context')
    # ### end Alembic commands ###
