"""drop decisions outcome column

Revision ID: e472f9c1e70e
Revises: bfd704ecac83
Create Date: 2026-04-06 23:36:15.129487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e472f9c1e70e'
down_revision: Union[str, Sequence[str], None] = 'bfd704ecac83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('decisions', 'outcome')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('decisions', sa.Column('outcome', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
