"""Pydantic schemas module."""

from schemas.admin import (
    AdminActionResponse,
    AdminEventApproveRequest,
    AdminEventManualRequest,
    AdminEventSelectRequest,
    AdminEventSelectResponse,
    AdminEventSwapRequest,
    AdminModelResetRequest,
)
from schemas.ai_model import (
    AIModelBase,
    AIModelBriefResponse,
    AIModelPerformanceResponse,
    AIModelResponse,
    LeaderboardEntry,
    LeaderboardResponse,
)
from schemas.bet import (
    BetBase,
    BetCreate,
    BetDetailResponse,
    BetPosition,
    BetResponse,
    ModelSettlementResult,
    SettlementResponse,
    SettlementResultResponse,
)
from schemas.betting_session import (
    BettingSessionBase,
    BettingSessionDetailResponse,
    BettingSessionResponse,
    MessageActionType,
    MessageType,
    SessionMessageAction,
    SessionMessageCreate,
    SessionMessageResponse,
    SessionPosition,
    SessionStatus,
)
from schemas.common import BaseSchema, PaginatedResponse, TimestampSchema
from schemas.event import (
    EventBase,
    EventBriefResponse,
    EventCreate,
    EventDetailResponse,
    EventOutcome,
    EventResponse,
    EventStatus,
    EventSummaryResponse,
    ModelPositionResponse,
    PriceHistoryResponse,
)
from schemas.websocket import (
    WSBetMessage,
    WSClientAction,
    WSClientMessage,
    WSErrorMessage,
    WSPriceUpdate,
    WSReasoningMessage,
    WSServerMessage,
    WSServerMessageType,
    WSSessionStatusMessage,
    WSSettlementMessage,
    WSViewerCountMessage,
)

__all__ = [
    # Common
    "BaseSchema",
    "PaginatedResponse",
    "TimestampSchema",
    # AI Model
    "AIModelBase",
    "AIModelBriefResponse",
    "AIModelPerformanceResponse",
    "AIModelResponse",
    "LeaderboardEntry",
    "LeaderboardResponse",
    # Event
    "EventBase",
    "EventBriefResponse",
    "EventCreate",
    "EventDetailResponse",
    "EventOutcome",
    "EventResponse",
    "EventStatus",
    "EventSummaryResponse",
    "ModelPositionResponse",
    "PriceHistoryResponse",
    # Betting Session
    "BettingSessionBase",
    "BettingSessionDetailResponse",
    "BettingSessionResponse",
    "MessageActionType",
    "MessageType",
    "SessionMessageAction",
    "SessionMessageCreate",
    "SessionMessageResponse",
    "SessionPosition",
    "SessionStatus",
    # Bet
    "BetBase",
    "BetCreate",
    "BetDetailResponse",
    "BetPosition",
    "BetResponse",
    "ModelSettlementResult",
    "SettlementResponse",
    "SettlementResultResponse",
    # WebSocket
    "WSBetMessage",
    "WSClientAction",
    "WSClientMessage",
    "WSErrorMessage",
    "WSPriceUpdate",
    "WSReasoningMessage",
    "WSServerMessage",
    "WSServerMessageType",
    "WSSessionStatusMessage",
    "WSSettlementMessage",
    "WSViewerCountMessage",
    # Admin
    "AdminActionResponse",
    "AdminEventApproveRequest",
    "AdminEventManualRequest",
    "AdminEventSelectRequest",
    "AdminEventSelectResponse",
    "AdminEventSwapRequest",
    "AdminModelResetRequest",
]
